### ISSUE TITLE
iMM904 missing mitochondrial chromosome

### ISSUE THREAD

**Issue by jlerman44** [SBRG/bigg_models_data#2]
Hi Zak,

I tested going with
iMM904.xml     pmid:19321003   ncbi_assembly:GCF_000146045.2,NC_001224.1.gb

inside model-genome.txt  

Definitely need the ATP synthase :)

Best,
Josh

**Comment by zakandrewking** [comment]
thanks josh. I'm sorry this took forever! but i'm testing it now for the next release.
