### ISSUE TITLE
Wrong INCHI key in JSON version of E. coli core

### ISSUE THREAD

**Issue by draeger** [SBRG/bigg_models_data#7]
The model http://bigg.ucsd.edu/models/e_coli_core has the following wrong INCHI key for D-Glycerate 2-phosphate: `GXIURPTVHJPJLF-UWTATZPHSA-K` but the last letter should be an `N` (not `K`): `GXIURPTVHJPJLF-UWTATZPHSA-N`

**Comment by zakandrewking** [comment]
We bring in the InChIs straight from MetaNetX: https://www.metanetx.org/chem_info/MNXM275

I believe their approach is to calculate the most-common form of the metabolite at pH 7 (ChEBI lists it as such https://www.ebi.ac.uk/chebi/searchId.do?chebiId=58289), which will not always match the formula in a given model. So this is an expected deviation.
